spring:
  application:
    name: notification-service

  jackson:
    time-zone: Europe/Istanbul

  datasource:
    url: jdbc:postgresql://localhost:5432/nrs_finance?currentSchema=public
    username: nrs
    password: nrs123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/nrs-finance

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.nurseli.notificationservice.event
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.nurseli.notificationservice.event.NotificationRequestedEvent
server:
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized


gmail:
  client-id: ${GMAIL_CLIENT_ID:}
  client-secret: ${GMAIL_CLIENT_SECRET:}
  refresh-token: ${GMAIL_REFRESH_TOKEN:}
  from-address: ${GMAIL_FROM_ADDRESS:}


notification:
  test-email: ${NOTIFICATION_TEST_EMAIL:}
keycloak:
  auth-server-url: http://localhost:8081
  realm: nrs-finance
  client-id: nrs-finance-backend
  client-secret: ${KEYCLOAK_NOTIFICATION_S2S_SECRET:}
finance:
  base-url: ${FINANCE_BASE_URL:http://localhost:8085}