server:
  port: 8090
spring:
  application:
    name: log-consumer-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: whale-detector
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.nurseli.logconsumer.event
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.nurseli.logconsumer.event.TransactionCreatedEvent

  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info
opensearch:
  host: localhost
  port: 9200