spring:
  application:
    name: finance-service

  # 🔥 Tüm altyapı ayarları 'spring' altında toplanmalı
  kafka:
    bootstrap-servers: nrs-kafka:9093  # 🔥 Docker'da internal port
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
          spring.json.add.type.headers: false
    consumer:
      group-id: finance-whale-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  datasource:
    url: jdbc:postgresql://nrs-postgres:5432/nrs_finance
    username: nrs
    password: nrs123
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: nrs-redis
      port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://nrs-keycloak:8081/realms/nrs-finance

# Spring dışındaki özel tanımların
market-data:
  base-url: http://nrs-market-data:8083

app:
  rate-limit:
    enabled: true
    max-requests-per-minute: 20
    window-sec: 60
  suspicious:
    enabled: true
    max-transactions-per-minute: 1
    high-amount-threshold: 100