spring:
  application:
    name: finance-service

  datasource:
    url: jdbc:postgresql://localhost:5432/nrs_finance
    username: nrs
    password: nrs123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/nrs-finance

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false
        spring.json.use.type.headers: false

        # 🔥 EN KRİTİK KISIM (Instant problemi çözülür)
        spring.json.value.default.type: java.lang.Object

