{
 "title": "NRS - Observability",
 "tags": [
  "nrs",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Volume (RPS) - All Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_server_requests_seconds_count[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Error Rate (5xx) - All Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_server_requests_seconds_count{status=~\"5..\"}[5m])) / sum by (job) (rate(http_server_requests_seconds_count[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "API Response Time P95 (seconds) - All Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_server_requests_seconds_sum[5m]))\r\n/\r\nsum by (job) (rate(http_server_requests_seconds_count[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Service Health (UP)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  }
 ]
}