spring:
  application:
    name: metrics-service

  jackson:
    time-zone: Europe/Istanbul

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: metrics-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8084

opensearch:
  host: localhost
  port: 9200

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha



