-- Opsiyonel: artık üretilmeyen bildirim tiplerini temizler (finance-service 2026-05-22 sonrası).
-- Üretimde çalıştırmadan önce yedek alın. Varsayılan: SADECE geliştirme / staging.
--
-- Etkilenen tipler (kod tabanında yayımlanmıyor):
--   FUND_REQUEST_*, SUSPICIOUS_ACTIVITY, REVIEW_*, ACCOUNT_FROZEN, ACCOUNT_UNFROZEN
--
-- Aktif tipler (SİLMEYİN): REAL_RETURN_*, PORTFOLIO_*, PRICE_ALERT_*, USER_LOGIN_*,
--   USER_REGISTERED, SYSTEM_ERROR

-- Önizleme:
-- SELECT type, COUNT(*) FROM nrs_notification.notifications
-- WHERE type IN (
--   'FUND_REQUEST_CREATED','FUND_REQUEST_APPROVED','FUND_REQUEST_REJECTED',
--   'SUSPICIOUS_ACTIVITY','REVIEW_TASK_CREATED','REVIEW_COMPLETED',
--   'ACCOUNT_FROZEN','ACCOUNT_UNFROZEN'
-- ) GROUP BY type;

-- DELETE FROM nrs_notification.notifications
-- WHERE type IN (
--   'FUND_REQUEST_CREATED','FUND_REQUEST_APPROVED','FUND_REQUEST_REJECTED',
--   'SUSPICIOUS_ACTIVITY','REVIEW_TASK_CREATED','REVIEW_COMPLETED',
--   'ACCOUNT_FROZEN','ACCOUNT_UNFROZEN'
-- );
