#!/usr/bin/env bash
# Generate docs/api/endpoints.md from static controller scan (+ optional live OpenAPI).
# No Python. Requires: bash, awk, sort, curl (live), jq (live).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DOCS_API="$ROOT/docs/api"
ENDPOINTS_MD="$DOCS_API/endpoints.md"
OPENAPI_DIR="$DOCS_API/openapi"
LIVE=false
EXPORT=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --live) LIVE=true ;;
    --export-openapi) EXPORT=true; LIVE=true ;;
    -h|--help)
      echo "Usage: bash tools/generate_api_catalog.sh [--live] [--export-openapi]"
      exit 0
      ;;
  esac
  shift
done

# shellcheck source=tools/lib/api-scan.sh
source "$ROOT/tools/lib/api-scan.sh"

mkdir -p "$DOCS_API"

TSV="$(mktemp)"
LIVE_LOG="$(mktemp)"
trap 'rm -f "$TSV" "$LIVE_LOG"' EXIT

scan_all | sort -u -t$'\t' -k3,3 -k1,1 -k2,2 >"$TSV"

static_count=$(wc -l <"$TSV" | tr -d ' ')
openapi_count=0
: >"$LIVE_LOG"

fetch_openapi() {
  local svc="$1"
  shift
  local url doc
  for base in "$@"; do
    url="${base%/}/v3/api-docs"
    if doc=$(curl -fsS --max-time 4 "$url" 2>/dev/null); then
      echo "$svc	$url" >>"$LIVE_LOG"
      if [[ "$EXPORT" == true ]]; then
        mkdir -p "$OPENAPI_DIR"
        printf '%s\n' "$doc" >"$OPENAPI_DIR/${svc}.json"
        echo "[catalog] exported $OPENAPI_DIR/${svc}.json"
      fi
      printf '%s\n' "$doc" | jq -r --arg svc "$svc" '
        .paths | to_entries[] | .key as $path | .value | to_entries[] |
        select(.key | test("^(get|post|put|delete|patch)$"; "i")) |
        select($path | startswith("/api")) |
        [$svc, (.key | ascii_upcase), $path, (.value.summary // .value.operationId // "")] | @tsv
      ' 2>/dev/null || true
      return 0
    fi
  done
  return 1
}

if [[ "$LIVE" == true ]]; then
  LIVE_TSV="$(mktemp)"
  {
    fetch_openapi "finance-service" "http://localhost:8085" "http://localhost:8080" || true
    fetch_openapi "marketdata" "http://localhost:8086" "http://localhost:8083" || true
    fetch_openapi "notification-service" "http://localhost:8091" "http://localhost:8089" || true
    fetch_openapi "log-consumer-service" "http://localhost:8090" "http://localhost:8087" || true
  } >"$LIVE_TSV" 2>/dev/null || true
  if [[ -s "$LIVE_TSV" ]]; then
    openapi_count=$(wc -l <"$LIVE_TSV" | tr -d ' ')
    # merge: live rows override static on same service+method+path
    awk -F'\t' 'FNR==NR{static[$1 FS $2 FS $3]=$0; next}
      {key=$1 FS $2 FS $3; live[key]=$0}
      END{
        for (k in static) if (!(k in live)) print static[k]
        for (k in live) print live[k]
      }' "$TSV" "$LIVE_TSV" | sort -u -t$'\t' -k3,3 >"${TSV}.merged"
    mv "${TSV}.merged" "$TSV"
  fi
  rm -f "$LIVE_TSV"
fi

now="$(date -u +"%Y-%m-%d %H:%M UTC")"

cat >"$ENDPOINTS_MD" <<'HEADER'
# API Endpoint Catalog

HEADER

{
  echo "> Auto-generated by \`bash tools/generate_api_catalog.sh\`. Last run: **${now}**."
  echo "> Static scan: **${static_count}** endpoints · OpenAPI merge: **${openapi_count}** operations"
  echo ""
  echo "Regenerate:"
  echo ""
  echo '```bash'
  echo "bash tools/generate_api_catalog.sh"
  echo "bash tools/generate_api_catalog.sh --live"
  echo "bash tools/export_openapi.sh"
  echo '```'
  echo ""
  echo "See also: [README.md](./README.md), [response-standardization-inventory.md](./response-standardization-inventory.md)."
  echo ""
  echo "## Response envelope"
  echo ""
  echo "Most JSON endpoints return a unified envelope (finance \`ApiResponse\`, marketdata \`ApiEnvelope\`)."
  echo "Details: [response-standardization-inventory.md](./response-standardization-inventory.md)."
  echo ""
  echo "**Success example**"
  echo ""
  echo '```json'
  cat <<'JSON'
{
  "success": true,
  "data": { "...": "endpoint-specific payload" },
  "errors": null,
  "meta": { "correlationId": "optional" }
}
JSON
  echo '```'
  echo ""
  echo "**Error example**"
  echo ""
  echo '```json'
  cat <<'JSON'
{
  "success": false,
  "data": null,
  "errors": {
    "code": "VALIDATION_ERROR",
    "message": "Human-readable message",
    "path": "/api/example",
    "timestamp": "2026-05-22T12:00:00+03:00",
    "correlationId": "uuid",
    "details": {}
  }
}
JSON
  echo '```'
  echo ""
  echo "**Intentional non-envelope**"
  echo ""
  echo "- \`GET /api/fund-requests/receipts/{receiptId}\` — binary stream"
  echo "- \`/health/**\`, \`/internal/**\` (service-internal)"
  echo ""
} >>"$ENDPOINTS_MD"

if [[ -s "$LIVE_LOG" ]]; then
  echo "## Live OpenAPI sources" >>"$ENDPOINTS_MD"
  echo "" >>"$ENDPOINTS_MD"
  while IFS=$'\t' read -r svc url; do
    echo "- **${svc}**: \`${url}\`" >>"$ENDPOINTS_MD"
  done <"$LIVE_LOG"
  echo "" >>"$ENDPOINTS_MD"
fi

echo "## Services overview" >>"$ENDPOINTS_MD"
echo "" >>"$ENDPOINTS_MD"
echo "| Service | \`/api/**\` endpoints |" >>"$ENDPOINTS_MD"
echo "|---------|---------------------|" >>"$ENDPOINTS_MD"
awk -F'\t' '{c[$1]++} END{for (s in c) print s, c[s]}' "$TSV" | sort | while read -r svc n; do
  echo "| ${svc} | ${n} |" >>"$ENDPOINTS_MD"
done
echo "" >>"$ENDPOINTS_MD"

append_section_grep() {
  local title="$1"
  local regex="$2"
  local service_filter="${3:-}"
  local section_file
  section_file="$(mktemp)"
  if [[ -n "$service_filter" ]]; then
    awk -F'\t' -v re="$regex" -v s="$service_filter" '$1 == s && $3 ~ re {print}' "$TSV" | sort -u >"$section_file"
  else
    awk -F'\t' -v re="$regex" '$3 ~ re {print}' "$TSV" | sort -u >"$section_file"
  fi
  if [[ ! -s "$section_file" ]]; then
    rm -f "$section_file"
    return
  fi
  {
    echo "## ${title}"
    echo ""
    echo "| Method | Path | Service | Summary |"
    echo "|--------|------|---------|---------|"
    while IFS=$'\t' read -r svc method path summary; do
      [[ -z "$summary" ]] && summary="—"
      echo "| \`${method}\` | \`${path}\` | ${svc} | ${summary} |"
    done < <(sort -t$'\t' -k3,3 -k2,2 "$section_file")
    echo ""
  } >>"$ENDPOINTS_MD"
  rm -f "$section_file"
}

append_section_grep "Auth & registration" '^/api/(users/|public/register)'
append_section_grep "Portfolio" '^/api/portfolio'
append_section_grep "Market (finance proxy)" '^/api/market/' "finance-service"
append_section_grep "Bank rates" '^/api/market/bank-rates'
append_section_grep "Admin" '^/api/admin/'
append_section_grep "News" '^/api/news/'

# Market data only rows (marketdata service)
{
  echo "## Market (marketdata)"
  echo ""
  echo "| Method | Path | Service | Summary |"
  echo "|--------|------|---------|---------|"
  awk -F'\t' '$1 == "marketdata" && $3 ~ /^\/api\/(market|news)\// {
    s = ($4 == "" ? "—" : $4)
    printf "| `%s` | `%s` | %s | %s |\n", $2, $3, $1, s
  }' "$TSV" | sort -t'|' -k3
  echo ""
} >>"$ENDPOINTS_MD"

echo "## Full catalog by service" >>"$ENDPOINTS_MD"
echo "" >>"$ENDPOINTS_MD"
for svc in finance-service marketdata notification-service log-consumer-service; do
  count=$(awk -F'\t' -v s="$svc" '$1==s{c++} END{print c+0}' "$TSV")
  [[ "$count" == "0" ]] && continue
  echo "### ${svc}" >>"$ENDPOINTS_MD"
  echo "" >>"$ENDPOINTS_MD"
  echo "| Method | Path |" >>"$ENDPOINTS_MD"
  echo "|--------|------|" >>"$ENDPOINTS_MD"
  awk -F'\t' -v s="$svc" '$1==s{printf "| `%s` | `%s` |\n", $2, $3}' "$TSV" | sort -t'|' -k3 >>"$ENDPOINTS_MD"
  echo "" >>"$ENDPOINTS_MD"
done

total=$(wc -l <"$TSV" | tr -d ' ')
echo "[catalog] wrote $ENDPOINTS_MD ($total endpoints)"

if [[ "$LIVE" == true && ! -s "$LIVE_LOG" ]]; then
  echo "[catalog] warn: --live set but no service responded; output is static-only" >&2
fi
