server:
  port: 8083

spring:
  application:
    name: market-data-service

  datasource:
    url: jdbc:postgresql://nrs-market-postgres:5432/nrs_market
    username: nrs
    password: nrs123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: nrs-redis
      port: 6379