server:
  port: 8089

spring:
  application:
    name: whale-analytics-service

  jackson:
    time-zone: Europe/Istanbul

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false
        spring.json.use.type.headers: false

  data:
    redis:
      host: localhost
      port: 6379
management:
  endpoints:
    web:
      exposure:
        include: health,info
whale:
  thresholds:
    l1:
      single-tx: 250
      daily-volume: 1000000
      hourly-count: 1
    l2:
      single-tx: 500000
      daily-volume: 5000000
      hourly-count: 20
    l3:
      single-tx: 1000000
      daily-volume: 20000000
      hourly-count: 50
